collections:
  authors:
    output: true
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
        layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
        layout: "post"
        excerpt_separator: <!--more-->
  - scope:
      path: ""
    values:
        layout: "default"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
